### ISSUE TITLE
feat: Add logging in via token

### ISSUE THREAD

**Issue by Childish-Stephan** [revenge-mod/revenge-bundle#55]
There's this feature on aliucord which allows users to add their account by using their account token. This means that even if you lost your account because of 2FA, you would still be fine.

I hope to see this on revenge

**Comment by Cristiandis** [comment]
> There's this feature on aliucord which allows users to add their account by using their account token. This means that even if you lost your account because of 2FA, you would still be fine.
> 
> I hope to see this on revenge


there's a plugin that lets you login with a token:
https://vd-plugins.github.io/proxy/meqativ.github.io/dumsane/GetToken/

**Comment by oSumAtrIX** [comment]
This repo is not for plugins
